"""
LabGym.subsystems.shared.io.filesystem

Helpers for reading and writing spreadsheet artifacts

SAFE TO IMPORT from any layer; has **no** wx or OpenCV dependencies.
"""

from __future__ import annotations

# Standard library
import os
import shutil

# Third-party
import pandas as pd


# ADDEDFRM LabGym.core.tools
def parse_all_events_file(path_to_events):

	'''
	This function is used to parse an all_events.xlsx file and convert it into
	a dict 'event_probability', a list 'time_points', and a list 'behavior_names'.

	path_to_events: The path to the 'all_events.xlsx' file

	event_probability is a dictionary with the keys as the ID of each animal / object
	and the values are lists of lists, where each sub-list has a length of 2 and is
	in one of the following formats:

		- ['NA', -1]
		- [behavior, probability], where behavior is the name of the behavior
		and probability is a float between 0 and 1.

	time_points is a list of floats containing the time points of the analysis duration.
	'''

	df=pd.read_excel(path_to_events)

	event_probability={}
	time_points=[]
	behavior_names=[]

	for col_name,col in df.items():

		if col_name=='time/ID':

			time_points=[float(i) for i in col]

		else:

			idx=int(col_name)
			event_probability[idx]=[['NA',-1]]*len(time_points)
			for n,i in enumerate(col):
				event=eval(i)
				behavior=event[0]
				if behavior!='NA':
					if behavior not in behavior_names:
						behavior_names.append(behavior)
					event_probability[idx][n]=event

	behavior_names.sort()

	return (event_probability,time_points,behavior_names)


# ADDEDFRM LabGym.core.tools
def sort_examples_from_csv(path_to_examples,out_path):

	'''
	This function is used to sort behavior examples generated by LabGym according to
	the manual labeling from other sources. It inputs the unsorted behavior examples
	generated by LabGym and a .csv file that stores the frame-wise behavior labels,
	and sort the unsorted examples into different behavior categories (labels) that
	can be used to train a Categorizer in LabGym.

	path_to_examples: The folder that stores all unsorted examples generated by LabGym.
	The .csv file should also be in this folder.
	out_path: the folder to store the sorted behavior examples
	'''

	path_to_csv=None
	path_to_animations=[]

	for i in os.listdir(path_to_examples):
		if i.endswith('.csv'):
			path_to_csv=os.path.join(path_to_examples,i)
		if i.endswith('.avi'):
			path_to_animations.append(os.path.join(path_to_examples,i))

	if path_to_csv is None or len(path_to_animations)==0:

		print('No .csv file or behavior example!')

	else:

		annotation=pd.read_csv(path_to_csv)
		for i in list(annotation.columns):
			if i!='Unnamed: 0':
				os.makedirs(os.path.join(out_path,i),exist_ok=True)

		for path_to_animation in path_to_animations:
			basename=os.path.basename(path_to_animation)
			path_to_pattern_image=os.path.splitext(path_to_animation)[0]+'.jpg'
			frame_index=int(basename.split('_len')[0].split('_')[-1])
			row_in_annotation=annotation.loc[frame_index]
			for behavior_name,score in row_in_annotation.items():
				if str(behavior_name)!='Unnamed: 0':
					if score==1 and os.path.exists(path_to_animation) and os.path.exists(path_to_pattern_image):
						shutil.move(path_to_animation,os.path.join(out_path,str(behavior_name),basename))
						shutil.move(path_to_pattern_image,os.path.join(out_path,str(behavior_name),os.path.splitext(basename)[0]+'.jpg'))

	print('Sorting completed!')