name: CI

on:
  pull_request:
  # Enable running CI from the GitHub GUI (see https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch)
  workflow_dispatch:

jobs:
  tests:
    name: Tests (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Ubuntu: system libs installed before Python envs are made
      - name: Install system dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: ./.github/scripts/ubuntu_runtime_deps.sh
       
      - name: Install Nox
        uses: wntrblm/nox@2024.03.02
        with:
          python-versions: "3.9, 3.10"
      - name: Run tests
        run: nox -s tests --verbose
            
        
